export type PackageCategory = "trekking" | "climbing" | "hiking" | "discovery" | "cultural" | "cycling"

export interface Package {
  id: string
  title: string
  category: PackageCategory
  image: string
  duration: string
  difficulty: "Easy" | "Moderate" | "Challenging" | "Extreme"
  price: number
  description: string
  highlights: string[]
  maxAltitude: string
  groupSize: string
  bestSeason: string
  longDescription: string
  itinerary: { day: string; title: string; description: string; altitude?: string }[]
  includes: string[]
  excludes: string[]
  gallery: string[]
  mapImage?: string
  startingPoint: string
  endingPoint: string
  accommodation: string
  meals: string
  transportation: string
  minAge: number
  fitnessLevel: string
}

export const packages: Package[] = [
  // Trekking Packages
  {
    id: "everest-base-camp",
    title: "Everest Base Camp Trek",
    category: "trekking",
    image: "/everest-base-camp-trek-mountain-view.jpg",
    duration: "14 Days",
    difficulty: "Moderate",
    price: 1850,
    description: "The classic journey to the foot of the world's highest peak through Sherpa villages and monasteries.",
    longDescription:
      "The Everest Base Camp Trek is the adventure of a lifetime, taking you through the heart of the Khumbu region to the base of the world's highest mountain. This iconic trek offers breathtaking views of towering Himalayan peaks, ancient Buddhist monasteries, and the warm hospitality of the Sherpa people. Walk in the footsteps of legendary mountaineers as you acclimatize through charming villages like Namche Bazaar and Tengboche, eventually reaching the famous Everest Base Camp at 5,364m and the stunning viewpoint of Kala Patthar.",
    highlights: [
      "Namche Bazaar",
      "Tengboche Monastery",
      "Kala Patthar viewpoint",
      "Sherpa culture",
      "Sagarmatha National Park",
    ],
    maxAltitude: "5,545m",
    groupSize: "2-12",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      {
        day: "1",
        title: "Arrival in Kathmandu",
        description: "Welcome meeting and trek briefing. Transfer to hotel.",
        altitude: "1,400m",
      },
      {
        day: "2",
        title: "Fly to Lukla, Trek to Phakding",
        description: "Scenic flight to Lukla and begin trekking through pine forests.",
        altitude: "2,610m",
      },
      {
        day: "3",
        title: "Trek to Namche Bazaar",
        description: "Cross suspension bridges and climb to the Sherpa capital.",
        altitude: "3,440m",
      },
      {
        day: "4",
        title: "Acclimatization Day in Namche",
        description: "Explore Namche, visit the museum and viewpoints.",
        altitude: "3,440m",
      },
      {
        day: "5",
        title: "Trek to Tengboche",
        description: "Walk through rhododendron forests to the famous monastery.",
        altitude: "3,860m",
      },
      {
        day: "6",
        title: "Trek to Dingboche",
        description: "Enter the alpine zone with stunning Ama Dablam views.",
        altitude: "4,410m",
      },
      {
        day: "7",
        title: "Acclimatization Day in Dingboche",
        description: "Rest day with optional hike to Nagarjun Hill.",
        altitude: "4,410m",
      },
      {
        day: "8",
        title: "Trek to Lobuche",
        description: "Pass memorials and enjoy dramatic mountain scenery.",
        altitude: "4,940m",
      },
      {
        day: "9",
        title: "Trek to Gorak Shep, Visit Base Camp",
        description: "Reach Everest Base Camp and witness the Khumbu Icefall.",
        altitude: "5,364m",
      },
      {
        day: "10",
        title: "Kala Patthar Sunrise, Trek to Pheriche",
        description: "Early morning hike for sunrise views, then descend.",
        altitude: "4,280m",
      },
      {
        day: "11",
        title: "Trek to Namche Bazaar",
        description: "Retrace steps through familiar terrain.",
        altitude: "3,440m",
      },
      {
        day: "12",
        title: "Trek to Lukla",
        description: "Final day of trekking through lower villages.",
        altitude: "2,860m",
      },
      {
        day: "13",
        title: "Fly to Kathmandu",
        description: "Morning flight back to Kathmandu. Free time for shopping.",
        altitude: "1,400m",
      },
      {
        day: "14",
        title: "Departure",
        description: "Transfer to airport for your onward journey.",
        altitude: "1,400m",
      },
    ],
    includes: [
      "Airport transfers",
      "Domestic flights (Kathmandu-Lukla-Kathmandu)",
      "All accommodation during trek",
      "All meals during trek",
      "Experienced English-speaking guide",
      "Porters (1 porter per 2 trekkers)",
      "Sagarmatha National Park permits",
      "TIMS card",
      "First aid kit",
      "Sleeping bag (if required)",
    ],
    excludes: [
      "International flights",
      "Nepal visa fees",
      "Travel insurance",
      "Personal trekking gear",
      "Tips for guides and porters",
      "Alcoholic beverages",
      "Hot showers and charging fees",
      "Emergency evacuation costs",
    ],
    gallery: [
      "/everest-base-camp.png",
      "/namche-bazaar-market.jpg",
      "/tengboche-monastery.jpg",
      "/kala-patthar-sunrise.jpg",
    ],
    startingPoint: "Lukla",
    endingPoint: "Lukla",
    accommodation: "Tea Houses / Lodges",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Domestic Flights + Trekking",
    minAge: 12,
    fitnessLevel: "Good fitness required. Prior trekking experience recommended.",
  },
  {
    id: "annapurna-circuit",
    title: "Annapurna Circuit Trek",
    category: "trekking",
    image: "/annapurna-circuit-thorong-la-pass.jpg",
    duration: "18 Days",
    difficulty: "Challenging",
    price: 1650,
    description: "A complete circumnavigation of the Annapurna massif crossing the famous Thorong La Pass.",
    longDescription:
      "The Annapurna Circuit is one of the world's greatest long-distance treks, offering an incredible diversity of landscapes, cultures, and experiences. From the subtropical lowlands to the high-altitude desert of Upper Mustang, you'll cross the challenging Thorong La Pass at 5,416m, visit the sacred temple of Muktinath, and witness some of the most spectacular mountain scenery on Earth. This classic trek takes you through traditional Hindu and Buddhist villages, lush forests, and barren high-altitude terrain.",
    highlights: [
      "Thorong La Pass (5,416m)",
      "Muktinath Temple",
      "Manang Valley",
      "Diverse landscapes",
      "Traditional villages",
    ],
    maxAltitude: "5,416m",
    groupSize: "2-10",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome and trek preparation.", altitude: "1,400m" },
      {
        day: "2",
        title: "Drive to Besisahar, Trek to Khudi",
        description: "Begin the journey into the Annapurna region.",
        altitude: "790m",
      },
      {
        day: "3",
        title: "Trek to Bahundanda",
        description: "Walk through rice terraces and villages.",
        altitude: "1,310m",
      },
      {
        day: "4",
        title: "Trek to Chamje",
        description: "Cross suspension bridges and waterfalls.",
        altitude: "1,430m",
      },
      { day: "5", title: "Trek to Dharapani", description: "Enter the Manang district.", altitude: "1,960m" },
      {
        day: "6",
        title: "Trek to Chame",
        description: "First views of Annapurna II and Lamjung Himal.",
        altitude: "2,710m",
      },
      {
        day: "7",
        title: "Trek to Pisang",
        description: "Walk through pine forests with mountain views.",
        altitude: "3,200m",
      },
      { day: "8", title: "Trek to Manang", description: "Explore the beautiful Manang Valley.", altitude: "3,540m" },
      {
        day: "9",
        title: "Acclimatization in Manang",
        description: "Rest day with optional hikes.",
        altitude: "3,540m",
      },
      { day: "10", title: "Trek to Yak Kharka", description: "Climb higher into alpine terrain.", altitude: "4,110m" },
      { day: "11", title: "Trek to Thorong Phedi", description: "Prepare for the pass crossing.", altitude: "4,450m" },
      {
        day: "12",
        title: "Cross Thorong La to Muktinath",
        description: "The big day! Cross the highest point.",
        altitude: "3,800m",
      },
      {
        day: "13",
        title: "Trek to Jomsom",
        description: "Descend through the Kali Gandaki Valley.",
        altitude: "2,720m",
      },
      { day: "14", title: "Trek to Tatopani", description: "Enjoy natural hot springs.", altitude: "1,190m" },
      {
        day: "15",
        title: "Trek to Ghorepani",
        description: "Climb to the famous viewpoint village.",
        altitude: "2,860m",
      },
      {
        day: "16",
        title: "Poon Hill Sunrise, Trek to Tikhedhunga",
        description: "Witness sunrise over the Himalayas.",
        altitude: "1,540m",
      },
      {
        day: "17",
        title: "Trek to Nayapul, Drive to Pokhara",
        description: "End the trek and relax in Pokhara.",
        altitude: "820m",
      },
      {
        day: "18",
        title: "Drive/Fly to Kathmandu, Departure",
        description: "Return to Kathmandu for departure.",
        altitude: "1,400m",
      },
    ],
    includes: [
      "All ground transportation",
      "Accommodation during trek",
      "All meals during trek",
      "Experienced guide and porters",
      "ACAP permit",
      "TIMS card",
      "First aid kit",
    ],
    excludes: [
      "International flights",
      "Nepal visa",
      "Travel insurance",
      "Personal gear",
      "Tips",
      "Beverages",
      "Hot showers",
    ],
    gallery: [
      "/thorong-la-pass-crossing.jpg",
      "/muktinath-temple.jpg",
      "/manang-village.jpg",
      "/poon-hill-sunrise.jpg",
    ],
    startingPoint: "Besisahar",
    endingPoint: "Nayapul",
    accommodation: "Tea Houses / Lodges",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Private Vehicle + Trekking",
    minAge: 14,
    fitnessLevel: "Excellent fitness required. High altitude experience recommended.",
  },
  {
    id: "langtang-valley",
    title: "Langtang Valley Trek",
    category: "trekking",
    image: "/langtang-valley-nepal.png",
    duration: "10 Days",
    difficulty: "Easy",
    price: 1200,
    description: "Explore the beautiful valley close to Kathmandu with stunning views and Tamang culture.",
    longDescription:
      "The Langtang Valley Trek offers an accessible yet rewarding Himalayan adventure just north of Kathmandu. Known as the valley of glaciers, this trek takes you through lush forests, traditional Tamang villages, and alpine meadows to the foot of Langtang Lirung (7,227m). Visit the ancient Kyanjin Gompa monastery, taste local yak cheese at the famous cheese factory, and enjoy panoramic views from Tserko Ri. This trek is perfect for those with limited time who still want an authentic mountain experience.",
    highlights: [
      "Kyanjin Gompa",
      "Tserko Ri viewpoint",
      "Cheese factory visit",
      "Tamang culture",
      "Langtang National Park",
    ],
    maxAltitude: "4,984m",
    groupSize: "2-12",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome meeting and preparation.", altitude: "1,400m" },
      { day: "2", title: "Drive to Syabrubesi", description: "Scenic drive through mountains.", altitude: "1,550m" },
      {
        day: "3",
        title: "Trek to Lama Hotel",
        description: "Walk through oak and rhododendron forests.",
        altitude: "2,380m",
      },
      {
        day: "4",
        title: "Trek to Langtang Village",
        description: "Enter the beautiful Langtang Valley.",
        altitude: "3,430m",
      },
      { day: "5", title: "Trek to Kyanjin Gompa", description: "Reach the monastery and explore.", altitude: "3,870m" },
      {
        day: "6",
        title: "Explore Kyanjin, Climb Tserko Ri",
        description: "Optional climb for panoramic views.",
        altitude: "4,984m",
      },
      { day: "7", title: "Trek to Lama Hotel", description: "Begin the descent.", altitude: "2,380m" },
      { day: "8", title: "Trek to Syabrubesi", description: "Return to the roadhead.", altitude: "1,550m" },
      { day: "9", title: "Drive to Kathmandu", description: "Return to the capital.", altitude: "1,400m" },
      { day: "10", title: "Departure", description: "Transfer to airport.", altitude: "1,400m" },
    ],
    includes: [
      "All ground transportation",
      "Accommodation",
      "All meals during trek",
      "Guide and porter",
      "National park fees",
      "TIMS card",
    ],
    excludes: ["International flights", "Visa", "Insurance", "Personal gear", "Tips", "Beverages"],
    gallery: [
      "/langtang-valley.png",
      "/kyanjin-gompa.jpg",
      "/tserko-ri-view.jpg",
      "/tamang-village.jpg",
    ],
    startingPoint: "Syabrubesi",
    endingPoint: "Syabrubesi",
    accommodation: "Tea Houses / Lodges",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Private Vehicle + Trekking",
    minAge: 10,
    fitnessLevel: "Moderate fitness. Suitable for beginners.",
  },
  {
    id: "manaslu-circuit",
    title: "Manaslu Circuit Trek",
    category: "trekking",
    image: "/manaslu-circuit-trek-nepal.jpg",
    duration: "16 Days",
    difficulty: "Challenging",
    price: 2100,
    description: "A remote and pristine trek around the eighth highest mountain in the world.",
    longDescription:
      "The Manaslu Circuit Trek is a hidden gem that rivals the famous Annapurna Circuit in beauty and cultural richness. Circling the world's eighth highest peak, this restricted-area trek offers an authentic Himalayan experience with fewer crowds. Cross the challenging Larkya La Pass at 5,160m, explore ancient Buddhist monasteries, and experience the unique culture of the Nubri and Tsum valleys. This trek is perfect for experienced trekkers seeking adventure off the beaten path.",
    highlights: [
      "Larkya La Pass",
      "Birendra Lake",
      "Traditional villages",
      "Buddhist monasteries",
      "Remote wilderness",
    ],
    maxAltitude: "5,160m",
    groupSize: "2-8",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome and preparation.", altitude: "1,400m" },
      { day: "2", title: "Drive to Soti Khola", description: "Begin the journey to Manaslu.", altitude: "730m" },
      { day: "3", title: "Trek to Machha Khola", description: "Walk along the Budhi Gandaki River.", altitude: "930m" },
      { day: "4", title: "Trek to Jagat", description: "Cross suspension bridges and waterfalls.", altitude: "1,340m" },
      { day: "5", title: "Trek to Deng", description: "Enter the restricted area.", altitude: "1,860m" },
      { day: "6", title: "Trek to Namrung", description: "Tibetan-influenced villages appear.", altitude: "2,660m" },
      { day: "7", title: "Trek to Samagaon", description: "Views of Manaslu peak.", altitude: "3,530m" },
      {
        day: "8",
        title: "Rest Day in Samagaon",
        description: "Explore Birendra Lake and monastery.",
        altitude: "3,530m",
      },
      { day: "9", title: "Trek to Samdo", description: "High altitude village near Tibet.", altitude: "3,860m" },
      { day: "10", title: "Acclimatization in Samdo", description: "Prepare for the pass.", altitude: "3,860m" },
      { day: "11", title: "Trek to Dharamsala", description: "Climb to the base of Larkya La.", altitude: "4,460m" },
      {
        day: "12",
        title: "Cross Larkya La to Bimthang",
        description: "Cross the pass and descend.",
        altitude: "3,720m",
      },
      { day: "13", title: "Trek to Dharapani", description: "Join the Annapurna Circuit trail.", altitude: "1,860m" },
      { day: "14", title: "Trek to Tal", description: "Continue through the valley.", altitude: "1,700m" },
      { day: "15", title: "Drive to Kathmandu", description: "Return to the capital.", altitude: "1,400m" },
      { day: "16", title: "Departure", description: "Transfer to airport.", altitude: "1,400m" },
    ],
    includes: [
      "All transportation",
      "Accommodation",
      "Meals during trek",
      "Guide and porters",
      "Special permits",
      "TIMS card",
      "First aid kit",
    ],
    excludes: ["International flights", "Visa", "Insurance", "Personal gear", "Tips", "Beverages"],
    gallery: [
      "/manaslu-peak.jpg",
      "/larkya-la-pass.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Soti Khola",
    endingPoint: "Dharapani",
    accommodation: "Tea Houses / Camping",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Private Vehicle + Trekking",
    minAge: 16,
    fitnessLevel: "Excellent fitness required. Prior high altitude experience necessary.",
  },
  {
    id: "gokyo-lakes",
    title: "Gokyo Lakes Trek",
    category: "trekking",
    image: "/placeholder.svg?height=600&width=800",
    duration: "12 Days",
    difficulty: "Moderate",
    price: 1750,
    description: "Discover the stunning turquoise glacial lakes with panoramic Himalayan views.",
    longDescription:
      "The Gokyo Lakes Trek is an alternative route in the Everest region that offers equally spectacular views with fewer crowds. Marvel at the stunning turquoise waters of the Gokyo Lakes, climb Gokyo Ri for sunrise views of Everest and four other 8,000m peaks, and walk on the massive Ngozumpa Glacier. This trek combines natural beauty with cultural experiences in traditional Sherpa villages.",
    highlights: ["Gokyo Ri", "Five glacial lakes", "Ngozumpa Glacier", "Everest views", "Sherpa villages"],
    maxAltitude: "5,357m",
    groupSize: "2-10",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome meeting.", altitude: "1,400m" },
      { day: "2", title: "Fly to Lukla, Trek to Phakding", description: "Begin the journey.", altitude: "2,610m" },
      { day: "3", title: "Trek to Namche Bazaar", description: "Climb to the Sherpa capital.", altitude: "3,440m" },
      { day: "4", title: "Acclimatization in Namche", description: "Rest and explore.", altitude: "3,440m" },
      { day: "5", title: "Trek to Dole", description: "Leave the main EBC trail.", altitude: "4,200m" },
      { day: "6", title: "Trek to Machhermo", description: "Continue climbing.", altitude: "4,470m" },
      { day: "7", title: "Trek to Gokyo", description: "Reach the first lake.", altitude: "4,790m" },
      {
        day: "8",
        title: "Gokyo Ri and Lakes Exploration",
        description: "Climb Gokyo Ri for sunrise.",
        altitude: "5,357m",
      },
      { day: "9", title: "Trek to Dole", description: "Begin descent.", altitude: "4,200m" },
      { day: "10", title: "Trek to Namche Bazaar", description: "Return to Namche.", altitude: "3,440m" },
      { day: "11", title: "Trek to Lukla", description: "Final trekking day.", altitude: "2,860m" },
      { day: "12", title: "Fly to Kathmandu, Departure", description: "Return and depart.", altitude: "1,400m" },
    ],
    includes: [
      "Flights Kathmandu-Lukla-Kathmandu",
      "Accommodation",
      "Meals during trek",
      "Guide and porters",
      "Permits",
      "TIMS card",
    ],
    excludes: ["International flights", "Visa", "Insurance", "Personal gear", "Tips"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Lukla",
    endingPoint: "Lukla",
    accommodation: "Tea Houses / Lodges",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Domestic Flights + Trekking",
    minAge: 12,
    fitnessLevel: "Good fitness required. Similar to EBC trek.",
  },

  // Climbing Packages
  {
    id: "island-peak",
    title: "Island Peak Climbing",
    category: "climbing",
    image: "/placeholder.svg?height=600&width=800",
    duration: "18 Days",
    difficulty: "Challenging",
    price: 2800,
    description: "Perfect introduction to high altitude mountaineering in the Everest region.",
    longDescription:
      "Island Peak (Imja Tse) at 6,189m is one of Nepal's most popular climbing peaks, offering an excellent introduction to Himalayan mountaineering. Combined with the classic Everest Base Camp trek, this expedition provides technical climbing training and the thrill of summiting a Himalayan peak. The climb involves glacier travel, fixed rope climbing, and basic ice climbing techniques, all with stunning views of Lhotse, Nuptse, and Makalu.",
    highlights: [
      "Technical climbing training",
      "Summit at 6,189m",
      "Everest views",
      "Glacier training",
      "Base Camp experience",
    ],
    maxAltitude: "6,189m",
    groupSize: "2-8",
    bestSeason: "Apr-May, Oct-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Gear check and briefing.", altitude: "1,400m" },
      { day: "2", title: "Fly to Lukla, Trek to Phakding", description: "Begin the approach.", altitude: "2,610m" },
      { day: "3", title: "Trek to Namche Bazaar", description: "Climb to Sherpa capital.", altitude: "3,440m" },
      { day: "4", title: "Acclimatization in Namche", description: "Rest and explore.", altitude: "3,440m" },
      { day: "5", title: "Trek to Tengboche", description: "Visit the famous monastery.", altitude: "3,860m" },
      { day: "6", title: "Trek to Dingboche", description: "Enter alpine zone.", altitude: "4,410m" },
      { day: "7", title: "Acclimatization in Dingboche", description: "Prepare for altitude.", altitude: "4,410m" },
      { day: "8", title: "Trek to Chhukung", description: "Move to climbing base.", altitude: "4,730m" },
      { day: "9", title: "Climbing Training", description: "Practice techniques.", altitude: "4,730m" },
      { day: "10", title: "Trek to Island Peak Base Camp", description: "Reach base camp.", altitude: "5,087m" },
      { day: "11", title: "Climb to High Camp", description: "Prepare for summit.", altitude: "5,600m" },
      { day: "12", title: "Summit Day, Return to Chhukung", description: "Summit and descend.", altitude: "4,730m" },
      { day: "13", title: "Reserve Day", description: "Weather contingency.", altitude: "4,730m" },
      { day: "14", title: "Trek to Tengboche", description: "Begin return journey.", altitude: "3,860m" },
      { day: "15", title: "Trek to Namche Bazaar", description: "Continue descent.", altitude: "3,440m" },
      { day: "16", title: "Trek to Lukla", description: "Final trekking day.", altitude: "2,860m" },
      { day: "17", title: "Fly to Kathmandu", description: "Return to capital.", altitude: "1,400m" },
      { day: "18", title: "Departure", description: "Transfer to airport.", altitude: "1,400m" },
    ],
    includes: [
      "Flights",
      "Accommodation",
      "Meals",
      "Climbing guide",
      "Porters",
      "Permits",
      "Climbing gear rental",
      "Group climbing equipment",
    ],
    excludes: ["International flights", "Visa", "Personal climbing gear", "Insurance", "Tips", "Personal expenses"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Lukla",
    endingPoint: "Lukla",
    accommodation: "Tea Houses + Camping",
    meals: "All Meals Included",
    transportation: "Domestic Flights + Trekking",
    minAge: 18,
    fitnessLevel: "Excellent fitness. Basic climbing experience preferred.",
  },
  {
    id: "mera-peak",
    title: "Mera Peak Climbing",
    category: "climbing",
    image: "/placeholder.svg?height=600&width=800",
    duration: "20 Days",
    difficulty: "Challenging",
    price: 3200,
    description: "Nepal's highest trekking peak with stunning views of five 8,000m peaks.",
    longDescription:
      "Mera Peak at 6,476m is Nepal's highest trekking peak, offering a non-technical but challenging climb with spectacular views of five of the world's fourteen 8,000m peaks including Everest, Lhotse, Makalu, Cho Oyu, and Kangchenjunga. The remote approach through the Hinku Valley adds to the adventure, taking you through pristine forests and traditional villages before reaching the glaciated summit slopes.",
    highlights: [
      "Summit at 6,476m",
      "Views of Everest, Lhotse, Cho Oyu",
      "Remote approach",
      "Hinku Valley",
      "Glacier climbing",
    ],
    maxAltitude: "6,476m",
    groupSize: "2-6",
    bestSeason: "Apr-May, Oct-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Briefing and gear check.", altitude: "1,400m" },
      { day: "2", title: "Fly to Lukla, Trek to Paiya", description: "Begin remote approach.", altitude: "2,730m" },
      { day: "3", title: "Trek to Pangkongma", description: "Through forests and villages.", altitude: "2,850m" },
      { day: "4", title: "Trek to Ningsow", description: "Cross high ridges.", altitude: "2,863m" },
      { day: "5", title: "Trek to Chhatra Khola", description: "Descend to river.", altitude: "2,800m" },
      { day: "6", title: "Trek to Kothe", description: "Enter Hinku Valley.", altitude: "3,600m" },
      { day: "7", title: "Trek to Thaknak", description: "Climb higher.", altitude: "4,350m" },
      { day: "8", title: "Trek to Khare", description: "Reach climbing base.", altitude: "5,045m" },
      { day: "9", title: "Acclimatization and Training", description: "Rest and practice.", altitude: "5,045m" },
      { day: "10", title: "Move to High Camp", description: "Establish high camp.", altitude: "5,800m" },
      { day: "11", title: "Summit Day", description: "Climb to summit.", altitude: "6,476m" },
      { day: "12", title: "Reserve Day", description: "Weather backup.", altitude: "5,800m" },
      { day: "13", title: "Descend to Khare", description: "Return to base.", altitude: "5,045m" },
      { day: "14", title: "Trek to Kothe", description: "Begin return trek.", altitude: "3,600m" },
      { day: "15", title: "Trek to Thuli Kharka", description: "Cross Zatrwa La.", altitude: "4,300m" },
      { day: "16", title: "Trek to Lukla", description: "Reach Lukla.", altitude: "2,860m" },
      { day: "17", title: "Reserve Day in Lukla", description: "Weather contingency.", altitude: "2,860m" },
      { day: "18", title: "Fly to Kathmandu", description: "Return to capital.", altitude: "1,400m" },
      { day: "19", title: "Free Day in Kathmandu", description: "Sightseeing and shopping.", altitude: "1,400m" },
      { day: "20", title: "Departure", description: "Transfer to airport.", altitude: "1,400m" },
    ],
    includes: [
      "All flights",
      "Accommodation",
      "All meals",
      "Climbing guide",
      "Porters",
      "Permits",
      "Climbing gear",
      "Group equipment",
    ],
    excludes: ["International flights", "Visa", "Personal gear", "Insurance", "Tips", "Extras"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Lukla",
    endingPoint: "Lukla",
    accommodation: "Tea Houses + Camping",
    meals: "All Meals Included",
    transportation: "Domestic Flights + Trekking",
    minAge: 18,
    fitnessLevel: "Excellent fitness essential. High altitude experience recommended.",
  },
  {
    id: "lobuche-peak",
    title: "Lobuche East Climbing",
    category: "climbing",
    image: "/placeholder.svg?height=600&width=800",
    duration: "16 Days",
    difficulty: "Extreme",
    price: 2950,
    description: "A more technical climb in the Everest region for experienced mountaineers.",
    longDescription:
      "Lobuche East (6,119m) offers a more technical climbing experience than Island Peak or Mera Peak, making it ideal for mountaineers looking to develop their skills. The climb involves steep ice and rock sections, fixed rope climbing, and requires good crampon and ice axe techniques. Located in the heart of the Khumbu region, the approach follows the classic Everest Base Camp trail with spectacular views throughout.",
    highlights: [
      "Technical ice and rock climbing",
      "Summit at 6,119m",
      "Khumbu views",
      "Advanced training",
      "Challenging ascent",
    ],
    maxAltitude: "6,119m",
    groupSize: "2-6",
    bestSeason: "Apr-May, Oct-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Gear check and briefing.", altitude: "1,400m" },
      { day: "2", title: "Fly to Lukla, Trek to Phakding", description: "Begin the approach.", altitude: "2,610m" },
      { day: "3", title: "Trek to Namche Bazaar", description: "Reach Sherpa capital.", altitude: "3,440m" },
      { day: "4", title: "Acclimatization Day", description: "Rest and explore.", altitude: "3,440m" },
      { day: "5", title: "Trek to Tengboche", description: "Visit the monastery.", altitude: "3,860m" },
      { day: "6", title: "Trek to Dingboche", description: "Enter alpine zone.", altitude: "4,410m" },
      { day: "7", title: "Acclimatization Day", description: "Prepare for altitude.", altitude: "4,410m" },
      { day: "8", title: "Trek to Lobuche", description: "Reach base area.", altitude: "4,940m" },
      { day: "9", title: "Move to Base Camp", description: "Establish base camp.", altitude: "5,100m" },
      { day: "10", title: "Climbing Training", description: "Technical practice.", altitude: "5,100m" },
      { day: "11", title: "Move to High Camp", description: "Prepare for summit.", altitude: "5,600m" },
      { day: "12", title: "Summit Day, Return to Base Camp", description: "Summit and descend.", altitude: "5,100m" },
      { day: "13", title: "Trek to Pheriche", description: "Begin return.", altitude: "4,280m" },
      { day: "14", title: "Trek to Namche", description: "Continue descent.", altitude: "3,440m" },
      { day: "15", title: "Trek to Lukla", description: "Final trekking day.", altitude: "2,860m" },
      { day: "16", title: "Fly to Kathmandu, Departure", description: "Return and depart.", altitude: "1,400m" },
    ],
    includes: [
      "Flights",
      "Accommodation",
      "Meals",
      "Climbing guide",
      "Porters",
      "Permits",
      "Technical gear",
      "Group equipment",
    ],
    excludes: ["International flights", "Visa", "Personal gear", "Insurance", "Tips"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Lukla",
    endingPoint: "Lukla",
    accommodation: "Tea Houses + Camping",
    meals: "All Meals Included",
    transportation: "Domestic Flights + Trekking",
    minAge: 18,
    fitnessLevel: "Excellent fitness. Prior climbing experience required.",
  },

  // Hiking Packages
  {
    id: "nagarkot-sunrise",
    title: "Nagarkot Sunrise Hike",
    category: "hiking",
    image: "/placeholder.svg?height=600&width=800",
    duration: "2 Days",
    difficulty: "Easy",
    price: 150,
    description: "Witness a spectacular sunrise over the Himalayas from the famous Nagarkot viewpoint.",
    longDescription:
      "The Nagarkot Sunrise Hike is the perfect introduction to Nepal's mountain scenery. Located just 32km from Kathmandu, Nagarkot offers one of the best Himalayan panoramas in the country, with views stretching from Dhaulagiri in the west to Everest in the east. This easy overnight trip includes a scenic drive, short hike through terraced farmland, and an unforgettable sunrise over the world's highest peaks.",
    highlights: [
      "Panoramic Himalayan views",
      "Sunrise photography",
      "Local village exploration",
      "Easy accessibility",
      "Traditional lunch",
    ],
    maxAltitude: "2,175m",
    groupSize: "2-15",
    bestSeason: "Year-round",
    itinerary: [
      {
        day: "1",
        title: "Drive to Nagarkot, Sunset Views",
        description: "Afternoon drive and evening at viewpoint.",
        altitude: "2,175m",
      },
      {
        day: "2",
        title: "Sunrise, Hike, Return to Kathmandu",
        description: "Early sunrise, village hike, return.",
        altitude: "2,175m",
      },
    ],
    includes: ["Transportation", "Hotel accommodation", "Breakfast and lunch", "Guide", "Entry fees"],
    excludes: ["Dinner", "Tips", "Personal expenses", "Beverages"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "Mountain Resort",
    meals: "Breakfast, Lunch",
    transportation: "Private Vehicle",
    minAge: 5,
    fitnessLevel: "Minimal fitness required. Suitable for all ages.",
  },
  {
    id: "shivapuri-hike",
    title: "Shivapuri National Park Hike",
    category: "hiking",
    image: "/placeholder.svg?height=600&width=800",
    duration: "1 Day",
    difficulty: "Easy",
    price: 75,
    description: "A refreshing day hike through lush forests with stunning views of Kathmandu Valley.",
    longDescription:
      "Shivapuri National Park, just north of Kathmandu, offers a perfect escape from the city's bustle. This day hike takes you through dense forests of oak, rhododendron, and pine, with chances to spot wildlife and over 300 species of birds. The trail offers panoramic views of the Kathmandu Valley and the snow-capped Himalayas beyond. It's an ideal choice for nature lovers and those seeking a quick but rewarding outdoor experience.",
    highlights: [
      "Dense forest trails",
      "Bird watching",
      "Kathmandu Valley views",
      "Wildlife spotting",
      "Fresh mountain air",
    ],
    maxAltitude: "2,732m",
    groupSize: "2-20",
    bestSeason: "Year-round",
    itinerary: [
      {
        day: "1",
        title: "Full Day Hike",
        description: "Morning pickup, forest hike, lunch, return by evening.",
        altitude: "2,732m",
      },
    ],
    includes: ["Transportation", "Guide", "Lunch", "Park entry fees", "Drinking water"],
    excludes: ["Tips", "Personal expenses", "Additional meals"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "None (Day Trip)",
    meals: "Lunch",
    transportation: "Private Vehicle",
    minAge: 6,
    fitnessLevel: "Basic fitness. Easy walking paths.",
  },
  {
    id: "poon-hill-hike",
    title: "Poon Hill Sunrise Hike",
    category: "hiking",
    image: "/placeholder.svg?height=600&width=800",
    duration: "4 Days",
    difficulty: "Easy",
    price: 450,
    description: "One of the most popular short hikes with breathtaking views of Annapurna and Dhaulagiri.",
    longDescription:
      "The Poon Hill Hike is Nepal's most popular short trek, offering spectacular mountain views without the demands of a longer expedition. Starting from Pokhara, this trek takes you through beautiful rhododendron forests (stunning in spring), traditional Gurung and Magar villages, and culminates with a magical sunrise from Poon Hill viewpoint. Watch the first rays of sun illuminate the Annapurna and Dhaulagiri ranges in an unforgettable display of natural beauty.",
    highlights: [
      "Ghorepani village",
      "Sunrise at Poon Hill",
      "Rhododendron forests",
      "Gurung culture",
      "Mountain panoramas",
    ],
    maxAltitude: "3,210m",
    groupSize: "2-15",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Drive to Nayapul, Trek to Tikhedhunga", description: "Begin the trek.", altitude: "1,540m" },
      { day: "2", title: "Trek to Ghorepani", description: "Climb through forests.", altitude: "2,860m" },
      {
        day: "3",
        title: "Poon Hill Sunrise, Trek to Tadapani",
        description: "Early morning viewpoint, continue trek.",
        altitude: "2,630m",
      },
      {
        day: "4",
        title: "Trek to Ghandruk, Drive to Pokhara",
        description: "Visit Gurung village, return to Pokhara.",
        altitude: "820m",
      },
    ],
    includes: [
      "Transportation",
      "Accommodation",
      "All meals during trek",
      "Guide and porter",
      "ACAP permit",
      "TIMS card",
    ],
    excludes: ["Personal expenses", "Tips", "Beverages", "Hot showers"],
    gallery: [
      "/poon-hill-sunrise.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Nayapul (Pokhara)",
    endingPoint: "Ghandruk (Pokhara)",
    accommodation: "Tea Houses",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Private Vehicle + Trekking",
    minAge: 8,
    fitnessLevel: "Basic to moderate fitness. Great for beginners.",
  },
  {
    id: "chandragiri-hike",
    title: "Chandragiri Hills Hike",
    category: "hiking",
    image: "/placeholder.svg?height=600&width=800",
    duration: "1 Day",
    difficulty: "Easy",
    price: 85,
    description: "Experience cable car ride and hiking with panoramic views of Kathmandu and Himalayas.",
    longDescription:
      "Chandragiri Hills offers a unique combination of modern convenience and natural beauty. Take the scenic cable car ride to the top of Chandragiri at 2,551m for spectacular 360-degree views of the Kathmandu Valley and the Himalayan range from Annapurna to Everest. Visit the historic Bhaleshwor Temple, enjoy lunch with a view, and take an easy hike through the surrounding forest. Perfect for families and those seeking mountain views without strenuous trekking.",
    highlights: [
      "Cable car experience",
      "Bhaleshwor Temple",
      "360-degree mountain views",
      "Easy forest trails",
      "Valley panorama",
    ],
    maxAltitude: "2,551m",
    groupSize: "2-20",
    bestSeason: "Year-round",
    itinerary: [
      {
        day: "1",
        title: "Full Day Excursion",
        description: "Drive, cable car, temple visit, hike, lunch, return.",
        altitude: "2,551m",
      },
    ],
    includes: ["Transportation", "Cable car tickets", "Guide", "Lunch", "Temple entry"],
    excludes: ["Tips", "Personal expenses", "Additional activities"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "None (Day Trip)",
    meals: "Lunch",
    transportation: "Private Vehicle + Cable Car",
    minAge: 4,
    fitnessLevel: "Minimal fitness required. Family-friendly.",
  },

  // Discovery Packages
  {
    id: "upper-mustang",
    title: "Upper Mustang Discovery",
    category: "discovery",
    image: "/placeholder.svg?height=600&width=800",
    duration: "14 Days",
    difficulty: "Moderate",
    price: 2400,
    description: "Explore the forbidden kingdom with its ancient Buddhist culture and lunar landscapes.",
    longDescription:
      "Upper Mustang, the former Kingdom of Lo, remained closed to outsiders until 1992, preserving one of the world's most intact Tibetan Buddhist cultures. This discovery trek takes you through a dramatic landscape of eroded cliffs, ancient caves, and whitewashed monasteries to the walled capital of Lo Manthang. Experience a living medieval culture, explore 1,000-year-old cave paintings, and witness the unique customs of this remote Himalayan region.",
    highlights: [
      "Lo Manthang walled city",
      "Ancient cave monasteries",
      "Tibetan culture",
      "Lunar landscapes",
      "Medieval kingdom",
    ],
    maxAltitude: "3,840m",
    groupSize: "2-10",
    bestSeason: "Mar-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome and preparation.", altitude: "1,400m" },
      { day: "2", title: "Fly to Pokhara, Drive to Jomsom", description: "Begin the journey.", altitude: "2,720m" },
      { day: "3", title: "Trek to Kagbeni", description: "Enter restricted area.", altitude: "2,810m" },
      { day: "4", title: "Trek to Chele", description: "Cross the Kali Gandaki.", altitude: "3,050m" },
      { day: "5", title: "Trek to Syangboche", description: "Climb through canyons.", altitude: "3,475m" },
      { day: "6", title: "Trek to Ghami", description: "Visit monasteries.", altitude: "3,520m" },
      { day: "7", title: "Trek to Tsarang", description: "Explore the ancient town.", altitude: "3,560m" },
      { day: "8", title: "Trek to Lo Manthang", description: "Reach the capital.", altitude: "3,840m" },
      { day: "9", title: "Explore Lo Manthang", description: "Full day in the walled city.", altitude: "3,840m" },
      { day: "10", title: "Trek to Dhakmar", description: "Alternative route back.", altitude: "3,820m" },
      { day: "11", title: "Trek to Ghiling", description: "Continue return.", altitude: "3,570m" },
      { day: "12", title: "Trek to Chhuksang", description: "Through red cliffs.", altitude: "2,980m" },
      { day: "13", title: "Trek to Jomsom", description: "Reach roadhead.", altitude: "2,720m" },
      { day: "14", title: "Fly to Pokhara, Kathmandu", description: "Return and departure.", altitude: "1,400m" },
    ],
    includes: [
      "All flights and transportation",
      "Accommodation",
      "All meals",
      "Guide and porters",
      "Special Upper Mustang permit",
      "ACAP permit",
    ],
    excludes: ["International flights", "Visa", "Insurance", "Personal items", "Tips", "Alcoholic beverages"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Jomsom",
    endingPoint: "Jomsom",
    accommodation: "Tea Houses / Local Guesthouses",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Domestic Flights + Trekking",
    minAge: 14,
    fitnessLevel: "Moderate fitness. Dry high altitude terrain.",
  },
  {
    id: "dolpo-region",
    title: "Dolpo Discovery Trek",
    category: "discovery",
    image: "/placeholder.svg?height=600&width=800",
    duration: "21 Days",
    difficulty: "Challenging",
    price: 3500,
    description: "One of the most remote and pristine regions of Nepal, untouched by modernity.",
    longDescription:
      "Dolpo is Nepal's most remote and least visited region, a land that time forgot. Made famous by Peter Matthiessen's 'The Snow Leopard,' this challenging trek takes you to the stunning Shey Phoksundo Lake, the deepest lake in Nepal, and through villages where ancient Bon Buddhist traditions still thrive. Experience a way of life unchanged for centuries, walk through landscapes that few outsiders have ever seen, and discover the true meaning of wilderness.",
    highlights: [
      "Shey Phoksundo Lake",
      "Ancient Bon culture",
      "Remote villages",
      "Snow leopard habitat",
      "Pristine wilderness",
    ],
    maxAltitude: "5,190m",
    groupSize: "2-8",
    bestSeason: "May-Oct",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Briefing and preparation.", altitude: "1,400m" },
      { day: "2", title: "Fly to Nepalgunj", description: "Transfer to lowlands.", altitude: "165m" },
      { day: "3", title: "Fly to Juphal, Trek to Dunai", description: "Enter Dolpo.", altitude: "2,140m" },
      { day: "4", title: "Trek to Tarakot", description: "Follow the river valley.", altitude: "2,540m" },
      { day: "5", title: "Trek to Laini Odara", description: "Climb higher.", altitude: "3,440m" },
      { day: "6", title: "Trek to Dho Tarap", description: "Enter the high valley.", altitude: "4,090m" },
      { day: "7", title: "Explore Dho Tarap", description: "Rest and explore Bon culture.", altitude: "4,090m" },
      { day: "8", title: "Trek to Numa La Base", description: "Prepare for pass.", altitude: "4,440m" },
      { day: "9", title: "Cross Numa La and Baga La", description: "Double pass crossing.", altitude: "5,190m" },
      { day: "10", title: "Trek to Shey Phoksundo Lake", description: "Reach the legendary lake.", altitude: "3,660m" },
      { day: "11", title: "Explore Phoksundo Lake", description: "Full day at the lake.", altitude: "3,660m" },
      { day: "12", title: "Trek to Ringmo", description: "Visit lakeside village.", altitude: "3,640m" },
      { day: "13-17", title: "Return Trek", description: "Trek back through various villages.", altitude: "Varies" },
      { day: "18", title: "Trek to Juphal", description: "Reach the airstrip.", altitude: "2,475m" },
      { day: "19", title: "Fly to Nepalgunj", description: "Return to lowlands.", altitude: "165m" },
      { day: "20", title: "Fly to Kathmandu", description: "Return to capital.", altitude: "1,400m" },
      { day: "21", title: "Departure", description: "Transfer to airport.", altitude: "1,400m" },
    ],
    includes: [
      "All flights",
      "Accommodation",
      "All meals",
      "Guide and porters",
      "Special Dolpo permit",
      "Camping equipment",
    ],
    excludes: ["International flights", "Visa", "Insurance", "Personal gear", "Tips"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Juphal",
    endingPoint: "Juphal",
    accommodation: "Camping + Basic Lodges",
    meals: "All Meals (Camp Cooking)",
    transportation: "Domestic Flights + Trekking",
    minAge: 18,
    fitnessLevel: "Excellent fitness essential. Remote and demanding terrain.",
  },
  {
    id: "tsum-valley",
    title: "Tsum Valley Trek",
    category: "discovery",
    image: "/placeholder.svg?height=600&width=800",
    duration: "15 Days",
    difficulty: "Moderate",
    price: 1900,
    description: "The sacred hidden valley with rich Tibetan Buddhist heritage and untouched culture.",
    longDescription:
      "Tsum Valley, meaning 'vivid' in Tibetan, is a sacred Himalayan pilgrimage valley hidden in the shadow of the Ganesh and Sringi Himal ranges. Opened to trekkers only in 2008, this remote valley has preserved its Tibetan Buddhist culture in pristine form. Walk past ancient chortens and mani walls, visit centuries-old monasteries including Mu Gompa, and explore the cave where the great saint Milarepa meditated. The welcoming Tsumba people maintain traditions that have disappeared elsewhere.",
    highlights: [
      "Mu Gompa",
      "Milarepa's cave",
      "Traditional Tsum villages",
      "Ancient monasteries",
      "Buddhist pilgrimage sites",
    ],
    maxAltitude: "3,700m",
    groupSize: "2-10",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome and preparation.", altitude: "1,400m" },
      { day: "2", title: "Drive to Soti Khola", description: "Begin journey to Tsum.", altitude: "730m" },
      { day: "3", title: "Trek to Machha Khola", description: "Along the Budhi Gandaki.", altitude: "930m" },
      { day: "4", title: "Trek to Jagat", description: "Enter the gorge.", altitude: "1,340m" },
      { day: "5", title: "Trek to Lokpa", description: "Turn into Tsum Valley.", altitude: "2,240m" },
      { day: "6", title: "Trek to Chumling", description: "First major Tsum village.", altitude: "2,386m" },
      { day: "7", title: "Trek to Chhokangparo", description: "Main village of Tsum.", altitude: "3,031m" },
      { day: "8", title: "Explore Upper Tsum", description: "Visit Mu Gompa.", altitude: "3,700m" },
      { day: "9", title: "Rest Day in Chhokangparo", description: "Explore monasteries.", altitude: "3,031m" },
      { day: "10", title: "Trek to Ripchet", description: "Begin return.", altitude: "2,470m" },
      { day: "11", title: "Trek to Gumba Lungdang", description: "Visit ancient monastery.", altitude: "3,200m" },
      { day: "12", title: "Trek to Lokpa", description: "Return through valley.", altitude: "2,240m" },
      { day: "13", title: "Trek to Tatopani", description: "Hot springs stop.", altitude: "1,340m" },
      { day: "14", title: "Drive to Kathmandu", description: "Return to capital.", altitude: "1,400m" },
      { day: "15", title: "Departure", description: "Transfer to airport.", altitude: "1,400m" },
    ],
    includes: [
      "Transportation",
      "Accommodation",
      "All meals during trek",
      "Guide and porters",
      "Special Tsum permit",
      "MCAP permit",
    ],
    excludes: ["International flights", "Visa", "Insurance", "Personal items", "Tips"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Soti Khola",
    endingPoint: "Soti Khola",
    accommodation: "Tea Houses / Local Homes",
    meals: "Breakfast, Lunch, Dinner",
    transportation: "Private Vehicle + Trekking",
    minAge: 12,
    fitnessLevel: "Moderate fitness. Cultural sensitivity required.",
  },

  // Cultural Tours
  {
    id: "kathmandu-heritage",
    title: "Kathmandu Valley Heritage",
    category: "cultural",
    image: "/placeholder.svg?height=600&width=800",
    duration: "5 Days",
    difficulty: "Easy",
    price: 650,
    description: "Discover the UNESCO World Heritage sites of the Kathmandu Valley.",
    longDescription:
      "The Kathmandu Valley is a living museum of art, architecture, and devotion. This comprehensive cultural tour takes you through seven UNESCO World Heritage Sites, including the ancient Durbar Squares of Kathmandu, Patan, and Bhaktapur, the sacred Hindu temple of Pashupatinath, and the great Buddhist stupas of Boudhanath and Swayambhunath. Experience living traditions, witness cremation ceremonies, observe monks in prayer, and explore medieval cities where craftsmen still practice ancient arts.",
    highlights: [
      "Pashupatinath Temple",
      "Boudhanath Stupa",
      "Three Durbar Squares",
      "Swayambhunath",
      "Traditional crafts",
    ],
    maxAltitude: "1,400m",
    groupSize: "2-15",
    bestSeason: "Year-round",
    itinerary: [
      {
        day: "1",
        title: "Arrival, Kathmandu Orientation",
        description: "Welcome and city overview.",
        altitude: "1,400m",
      },
      {
        day: "2",
        title: "Kathmandu Heritage Sites",
        description: "Durbar Square, Swayambhunath, Pashupatinath.",
        altitude: "1,400m",
      },
      {
        day: "3",
        title: "Patan and Boudhanath",
        description: "Explore the golden city and great stupa.",
        altitude: "1,400m",
      },
      { day: "4", title: "Bhaktapur Full Day", description: "Medieval city of devotees.", altitude: "1,400m" },
      { day: "5", title: "Final Exploration, Departure", description: "Shopping, departure.", altitude: "1,400m" },
    ],
    includes: [
      "Airport transfers",
      "Accommodation with breakfast",
      "Private guide",
      "Private transportation",
      "All entry fees",
      "Welcome and farewell dinners",
    ],
    excludes: ["International flights", "Visa", "Lunches", "Tips", "Personal expenses"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "Heritage Hotels",
    meals: "Breakfast, 2 Dinners",
    transportation: "Private Vehicle",
    minAge: 5,
    fitnessLevel: "Minimal fitness. Walking tours with some steps.",
  },
  {
    id: "buddhist-pilgrimage",
    title: "Buddhist Pilgrimage Tour",
    category: "cultural",
    image: "/placeholder.svg?height=600&width=800",
    duration: "8 Days",
    difficulty: "Easy",
    price: 950,
    description: "Visit the sacred Buddhist sites including Buddha's birthplace in Lumbini.",
    longDescription:
      "Nepal is the birthplace of Buddhism, and this pilgrimage tour takes you through the country's most sacred Buddhist sites. Begin in the Kathmandu Valley at the great stupas and monasteries, then journey to Lumbini, the UNESCO World Heritage Site where Siddhartha Gautama was born over 2,500 years ago. Visit the sacred garden, Maya Devi Temple, and monasteries built by Buddhist nations from around the world. Includes meditation sessions and teachings from resident monks.",
    highlights: ["Lumbini", "Swayambhunath", "Kopan Monastery", "Meditation sessions", "Boudhanath", "Pharping caves"],
    maxAltitude: "1,400m",
    groupSize: "2-15",
    bestSeason: "Year-round",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Welcome and introduction.", altitude: "1,400m" },
      {
        day: "2",
        title: "Kathmandu Buddhist Sites",
        description: "Swayambhunath, Boudhanath, Kopan.",
        altitude: "1,400m",
      },
      { day: "3", title: "Pharping Sacred Caves", description: "Visit meditation caves.", altitude: "1,600m" },
      {
        day: "4",
        title: "Fly to Bhairahawa, Drive to Lumbini",
        description: "Travel to Buddha's birthplace.",
        altitude: "100m",
      },
      { day: "5", title: "Lumbini Sacred Garden", description: "Full day exploration.", altitude: "100m" },
      { day: "6", title: "Lumbini Monasteries", description: "Visit international monasteries.", altitude: "100m" },
      { day: "7", title: "Return to Kathmandu", description: "Fly back to capital.", altitude: "1,400m" },
      { day: "8", title: "Departure", description: "Final meditation, airport transfer.", altitude: "1,400m" },
    ],
    includes: [
      "All transportation including flights",
      "Accommodation",
      "Breakfast and lunch",
      "Expert Buddhist guide",
      "Entry fees",
      "Meditation sessions",
    ],
    excludes: ["International flights", "Visa", "Dinners", "Tips", "Personal offerings"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "Hotels + Monastery Guesthouse",
    meals: "Breakfast, Lunch",
    transportation: "Private Vehicle + Domestic Flight",
    minAge: 8,
    fitnessLevel: "Minimal fitness. Peaceful walking tours.",
  },
  {
    id: "village-homestay",
    title: "Village Homestay Experience",
    category: "cultural",
    image: "/placeholder.svg?height=600&width=800",
    duration: "7 Days",
    difficulty: "Easy",
    price: 800,
    description: "Live with local families and experience authentic Nepali village life.",
    longDescription:
      "Experience the heart of Nepal by living with local families in traditional villages. This immersive homestay program takes you beyond the tourist trail to experience daily Nepali life firsthand. Learn to cook dal bhat, work in the fields, participate in local festivals, and create handcrafts with village artisans. Stay in traditional homes, share meals with your host family, and gain insights into rural life that most visitors never see. A truly transformative cultural experience.",
    highlights: [
      "Traditional cooking",
      "Farming activities",
      "Local festivals",
      "Craft workshops",
      "Family meals",
      "Village walks",
    ],
    maxAltitude: "2,000m",
    groupSize: "2-8",
    bestSeason: "Year-round",
    itinerary: [
      {
        day: "1",
        title: "Arrival, Drive to Village",
        description: "Meet host family, orientation.",
        altitude: "1,500m",
      },
      { day: "2", title: "Farm Life Experience", description: "Join daily farming activities.", altitude: "1,500m" },
      {
        day: "3",
        title: "Cooking and Crafts",
        description: "Learn traditional cooking and crafts.",
        altitude: "1,500m",
      },
      { day: "4", title: "Village Exploration", description: "Walk to nearby villages and sites.", altitude: "1,800m" },
      { day: "5", title: "Community Projects", description: "Participate in village activities.", altitude: "1,500m" },
      { day: "6", title: "Cultural Celebration", description: "Special farewell celebration.", altitude: "1,500m" },
      { day: "7", title: "Return to Kathmandu", description: "Farewell and departure.", altitude: "1,400m" },
    ],
    includes: [
      "All transportation",
      "Homestay accommodation",
      "All meals (home-cooked)",
      "Activities and workshops",
      "Cultural guide",
      "Welcome/farewell ceremonies",
    ],
    excludes: ["International flights", "Visa", "Personal gifts for family", "Tips", "Personal expenses"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "Traditional Homestay",
    meals: "All Meals (Home-Cooked)",
    transportation: "Private Vehicle",
    minAge: 6,
    fitnessLevel: "Minimal fitness. Village walking.",
  },

  // Cycling Packages
  {
    id: "kathmandu-valley-cycling",
    title: "Kathmandu Valley Cycling",
    category: "cycling",
    image: "/placeholder.svg?height=600&width=800",
    duration: "3 Days",
    difficulty: "Easy",
    price: 350,
    description: "Explore the historic Kathmandu Valley by bike, visiting temples and traditional villages.",
    longDescription:
      "Discover the Kathmandu Valley at your own pace on this scenic cycling tour. Pedal through ancient Newar towns, past terraced rice fields, and alongside centuries-old temples and shrines. This easy-paced tour takes you through the UNESCO World Heritage Site of Bhaktapur, the sacred temple of Changu Narayan, and into the countryside where traditional life continues unchanged. Perfect for cyclists of all levels who want to combine exercise with cultural exploration.",
    highlights: [
      "Bhaktapur Durbar Square",
      "Changu Narayan Temple",
      "Scenic rice paddies",
      "Newar villages",
      "Valley views",
    ],
    maxAltitude: "1,500m",
    groupSize: "2-12",
    bestSeason: "Year-round",
    itinerary: [
      { day: "1", title: "Kathmandu to Bhaktapur", description: "Cycle to the medieval city.", altitude: "1,400m" },
      { day: "2", title: "Bhaktapur to Nagarkot", description: "Climb to the viewpoint.", altitude: "2,175m" },
      {
        day: "3",
        title: "Nagarkot to Changu Narayan to Kathmandu",
        description: "Downhill through villages.",
        altitude: "1,400m",
      },
    ],
    includes: [
      "Quality mountain bike",
      "Helmet and gear",
      "Support vehicle",
      "Accommodation",
      "Breakfast and lunch",
      "Experienced guide",
    ],
    excludes: ["Dinners", "Tips", "Personal expenses", "Travel insurance"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Kathmandu",
    endingPoint: "Kathmandu",
    accommodation: "Hotels / Resorts",
    meals: "Breakfast, Lunch",
    transportation: "Cycling + Support Vehicle",
    minAge: 12,
    fitnessLevel: "Basic cycling fitness. Mostly flat with some hills.",
  },
  {
    id: "annapurna-cycling",
    title: "Annapurna Mountain Biking",
    category: "cycling",
    image: "/placeholder.svg?height=600&width=800",
    duration: "10 Days",
    difficulty: "Challenging",
    price: 1450,
    description: "An epic mountain biking adventure through the Annapurna region's diverse landscapes.",
    longDescription:
      "This challenging mountain biking expedition takes you through the heart of the Annapurna region, combining thrilling singletrack with spectacular Himalayan scenery. Ride from the subtropical lowlands to high-altitude villages, crossing suspension bridges, navigating rocky trails, and enjoying incredible downhill sections. Visit traditional Gurung villages, enjoy lakeside Pokhara, and experience the diversity of Nepal's landscapes from the seat of your bike.",
    highlights: [
      "Pokhara lakeside",
      "Mountain trails",
      "Traditional Gurung villages",
      "Suspension bridges",
      "Himalayan views",
    ],
    maxAltitude: "3,800m",
    groupSize: "2-8",
    bestSeason: "Mar-May, Sep-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Bike fitting and briefing.", altitude: "1,400m" },
      { day: "2", title: "Drive to Pokhara", description: "Transfer to lakeside.", altitude: "820m" },
      { day: "3", title: "Pokhara to Sarangkot", description: "Climb to viewpoint.", altitude: "1,600m" },
      { day: "4", title: "Ride to Naudanda", description: "Ridge line riding.", altitude: "1,500m" },
      { day: "5", title: "Ride to Ghandruk", description: "Climb to Gurung village.", altitude: "1,940m" },
      { day: "6", title: "Ride to Landruk", description: "Technical trails.", altitude: "1,565m" },
      { day: "7", title: "Ride to Dhampus", description: "Mountain views.", altitude: "1,650m" },
      { day: "8", title: "Ride to Pokhara", description: "Epic downhill.", altitude: "820m" },
      { day: "9", title: "Rest Day in Pokhara", description: "Relax or explore.", altitude: "820m" },
      { day: "10", title: "Return to Kathmandu, Departure", description: "Drive back.", altitude: "1,400m" },
    ],
    includes: [
      "Quality mountain bike",
      "All gear",
      "Support vehicle",
      "Accommodation",
      "All meals",
      "Experienced guide",
      "Permits",
    ],
    excludes: ["International flights", "Visa", "Tips", "Alcoholic beverages", "Personal insurance"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Pokhara",
    endingPoint: "Pokhara",
    accommodation: "Lodges / Guesthouses",
    meals: "All Meals",
    transportation: "Mountain Biking + Vehicle Support",
    minAge: 16,
    fitnessLevel: "Good cycling fitness. Technical riding experience helpful.",
  },
  {
    id: "mustang-cycling",
    title: "Upper Mustang Cycling",
    category: "cycling",
    image: "/placeholder.svg?height=600&width=800",
    duration: "14 Days",
    difficulty: "Challenging",
    price: 2200,
    description: "Cycle through the mystical kingdom of Mustang with its unique desert landscapes.",
    longDescription:
      "Experience the forbidden kingdom of Upper Mustang on two wheels in this epic cycling adventure. Ride through otherworldly landscapes of eroded cliffs, ancient caves, and wind-swept valleys to the walled city of Lo Manthang. This challenging expedition combines the cultural immersion of the classic Mustang trek with the thrill of mountain biking through one of the world's most unique landscapes. An unforgettable journey for adventurous cyclists.",
    highlights: [
      "Lo Manthang",
      "Ancient caves",
      "Tibetan Buddhist culture",
      "Desert landscapes",
      "Kali Gandaki Valley",
    ],
    maxAltitude: "3,840m",
    groupSize: "2-8",
    bestSeason: "Mar-Nov",
    itinerary: [
      { day: "1", title: "Arrival in Kathmandu", description: "Preparation and bike fitting.", altitude: "1,400m" },
      { day: "2", title: "Fly to Pokhara, Drive to Jomsom", description: "Begin the adventure.", altitude: "2,720m" },
      { day: "3", title: "Cycle to Kagbeni", description: "Along the Kali Gandaki.", altitude: "2,810m" },
      { day: "4", title: "Cycle to Chele", description: "Enter Upper Mustang.", altitude: "3,050m" },
      { day: "5", title: "Cycle to Syangboche", description: "Through canyon trails.", altitude: "3,475m" },
      { day: "6", title: "Cycle to Ghami", description: "Ancient monasteries.", altitude: "3,520m" },
      { day: "7", title: "Cycle to Tsarang", description: "Explore ruins.", altitude: "3,560m" },
      { day: "8", title: "Cycle to Lo Manthang", description: "Reach the capital.", altitude: "3,840m" },
      { day: "9", title: "Explore Lo Manthang", description: "Rest day in walled city.", altitude: "3,840m" },
      { day: "10", title: "Cycle to Dhakmar", description: "Alternative return route.", altitude: "3,820m" },
      { day: "11", title: "Cycle to Ghiling", description: "Continue south.", altitude: "3,570m" },
      { day: "12", title: "Cycle to Jomsom", description: "Epic descent.", altitude: "2,720m" },
      { day: "13", title: "Fly to Pokhara", description: "Rest day lakeside.", altitude: "820m" },
      { day: "14", title: "Return to Kathmandu, Departure", description: "Drive and depart.", altitude: "1,400m" },
    ],
    includes: [
      "Quality mountain bike",
      "All gear",
      "Flights and transportation",
      "Accommodation",
      "All meals",
      "Guide",
      "Upper Mustang permit",
    ],
    excludes: ["International flights", "Visa", "Tips", "Insurance", "Personal expenses"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Jomsom",
    endingPoint: "Jomsom",
    accommodation: "Local Guesthouses",
    meals: "All Meals",
    transportation: "Mountain Biking + Flights",
    minAge: 18,
    fitnessLevel: "Excellent cycling fitness. High altitude experience helpful.",
  },
  {
    id: "chitwan-cycling",
    title: "Chitwan Jungle Cycling",
    category: "cycling",
    image: "/placeholder.svg?height=600&width=800",
    duration: "4 Days",
    difficulty: "Easy",
    price: 420,
    description: "Combine cycling with wildlife exploration in the famous Chitwan National Park.",
    longDescription:
      "This unique adventure combines the thrill of cycling with the excitement of wildlife encounters in Chitwan National Park, home to rhinos, tigers, and elephants. Pedal through the buffer zone on quiet trails, passing through traditional Tharu villages and along the edge of the jungle. In between rides, enjoy jungle walks, canoe trips, and elephant encounters. A perfect blend of adventure, nature, and culture in Nepal's premier wildlife destination.",
    highlights: ["Jungle trails", "Wildlife viewing", "Tharu village visits", "Canoe safari", "Elephant encounters"],
    maxAltitude: "200m",
    groupSize: "2-10",
    bestSeason: "Oct-Mar",
    itinerary: [
      { day: "1", title: "Arrive in Chitwan", description: "Transfer, orientation, sunset ride.", altitude: "200m" },
      {
        day: "2",
        title: "Buffer Zone Cycling",
        description: "Ride through villages and jungle edge.",
        altitude: "200m",
      },
      {
        day: "3",
        title: "Wildlife Activities",
        description: "Canoe safari, jungle walk, evening ride.",
        altitude: "200m",
      },
      {
        day: "4",
        title: "Final Ride, Departure",
        description: "Morning ride, transfer to Kathmandu/Pokhara.",
        altitude: "200m",
      },
    ],
    includes: [
      "Mountain bike",
      "All gear",
      "Accommodation in jungle lodge",
      "All meals",
      "Wildlife activities",
      "Guide",
      "Park fees",
    ],
    excludes: ["Transportation to/from Chitwan", "Tips", "Personal expenses", "Insurance"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    startingPoint: "Sauraha (Chitwan)",
    endingPoint: "Sauraha (Chitwan)",
    accommodation: "Jungle Lodge",
    meals: "All Meals",
    transportation: "Cycling + Canoe + Walking",
    minAge: 10,
    fitnessLevel: "Basic cycling fitness. Flat terrain.",
  },
]

export const categories = [
  { id: "all", label: "All Packages" },
  { id: "trekking", label: "Trekking" },
  { id: "climbing", label: "Climbing" },
  { id: "hiking", label: "Hiking" },
  { id: "discovery", label: "Discovery Sites" },
  { id: "cultural", label: "Cultural Tours" },
  { id: "cycling", label: "Cycling" },
]

export const difficulties = ["Easy", "Moderate", "Challenging", "Extreme"]

export function getPackageById(id: string): Package | undefined {
  return packages.find((pkg) => pkg.id === id)
}

export function getRelatedPackages(currentId: string, category: PackageCategory, limit = 3): Package[] {
  return packages.filter((pkg) => pkg.category === category && pkg.id !== currentId).slice(0, limit)
}
