export type PackageCategory = "trekking" | "climbing" | "hiking" | "discovery" | "cultural" | "cycling"

export interface Package {
  id: string
  title: string
  category: PackageCategory
  image: string
  duration: string
  difficulty: "Easy" | "Moderate" | "Challenging" | "Extreme"
  price: number
  description: string
  highlights: string[]
  maxAltitude: string
  groupSize: string
  bestSeason: string
}

export const packages: Package[] = [
  // Trekking Packages
  {
    id: "everest-base-camp",
    title: "Everest Base Camp Trek",
    category: "trekking",
    image: "/everest-base-camp-trek-nepal-khumbu-glacier.jpg",
    duration: "14 Days",
    difficulty: "Moderate",
    price: 1850,
    description: "The classic journey to the foot of the world's highest peak through Sherpa villages and monasteries.",
    highlights: ["Namche Bazaar", "Tengboche Monastery", "Kala Patthar viewpoint"],
    maxAltitude: "5,545m",
    groupSize: "2-12",
    bestSeason: "Mar-May, Sep-Nov",
  },
  {
    id: "annapurna-circuit",
    title: "Annapurna Circuit Trek",
    category: "trekking",
    image: "/annapurna-circuit-trek-nepal-thorong-la-pass.jpg",
    duration: "18 Days",
    difficulty: "Challenging",
    price: 1650,
    description: "A complete circumnavigation of the Annapurna massif crossing the famous Thorong La Pass.",
    highlights: ["Thorong La Pass (5,416m)", "Muktinath Temple", "Manang Valley"],
    maxAltitude: "5,416m",
    groupSize: "2-10",
    bestSeason: "Mar-May, Sep-Nov",
  },
  {
    id: "langtang-valley",
    title: "Langtang Valley Trek",
    category: "trekking",
    image: "/langtang-valley-trek-nepal-mountain-scenery.jpg",
    duration: "10 Days",
    difficulty: "Easy",
    price: 1200,
    description: "Explore the beautiful valley close to Kathmandu with stunning views and Tamang culture.",
    highlights: ["Kyanjin Gompa", "Tserko Ri viewpoint", "Cheese factory visit"],
    maxAltitude: "4,984m",
    groupSize: "2-12",
    bestSeason: "Mar-May, Sep-Nov",
  },
  {
    id: "manaslu-circuit",
    title: "Manaslu Circuit Trek",
    category: "trekking",
    image: "/manaslu-circuit-trek-nepal-himalayan-trail.jpg",
    duration: "16 Days",
    difficulty: "Challenging",
    price: 2100,
    description: "A remote and pristine trek around the eighth highest mountain in the world.",
    highlights: ["Larkya La Pass", "Birendra Lake", "Traditional villages"],
    maxAltitude: "5,160m",
    groupSize: "2-8",
    bestSeason: "Mar-May, Sep-Nov",
  },
  {
    id: "gokyo-lakes",
    title: "Gokyo Lakes Trek",
    category: "trekking",
    image: "/placeholder.svg?height=400&width=600",
    duration: "12 Days",
    difficulty: "Moderate",
    price: 1750,
    description: "Discover the stunning turquoise glacial lakes with panoramic Himalayan views.",
    highlights: ["Gokyo Ri", "Five glacial lakes", "Ngozumpa Glacier"],
    maxAltitude: "5,357m",
    groupSize: "2-10",
    bestSeason: "Mar-May, Sep-Nov",
  },
  // Climbing Packages
  {
    id: "island-peak",
    title: "Island Peak Climbing",
    category: "climbing",
    image: "/placeholder.svg?height=400&width=600",
    duration: "18 Days",
    difficulty: "Challenging",
    price: 2800,
    description: "Perfect introduction to high altitude mountaineering in the Everest region.",
    highlights: ["Technical climbing training", "Summit at 6,189m", "Everest views"],
    maxAltitude: "6,189m",
    groupSize: "2-8",
    bestSeason: "Apr-May, Oct-Nov",
  },
  {
    id: "mera-peak",
    title: "Mera Peak Climbing",
    category: "climbing",
    image: "/placeholder.svg?height=400&width=600",
    duration: "20 Days",
    difficulty: "Challenging",
    price: 3200,
    description: "Nepal's highest trekking peak with stunning views of five 8,000m peaks.",
    highlights: ["Summit at 6,476m", "Views of Everest, Lhotse, Cho Oyu", "Remote approach"],
    maxAltitude: "6,476m",
    groupSize: "2-6",
    bestSeason: "Apr-May, Oct-Nov",
  },
  {
    id: "lobuche-peak",
    title: "Lobuche East Climbing",
    category: "climbing",
    image: "/placeholder.svg?height=400&width=600",
    duration: "16 Days",
    difficulty: "Extreme",
    price: 2950,
    description: "A more technical climb in the Everest region for experienced mountaineers.",
    highlights: ["Technical ice and rock climbing", "Summit at 6,119m", "Khumbu views"],
    maxAltitude: "6,119m",
    groupSize: "2-6",
    bestSeason: "Apr-May, Oct-Nov",
  },
  // Hiking Packages
  {
    id: "nagarkot-sunrise",
    title: "Nagarkot Sunrise Hike",
    category: "hiking",
    image: "/placeholder.svg?height=400&width=600",
    duration: "2 Days",
    difficulty: "Easy",
    price: 150,
    description: "Witness a spectacular sunrise over the Himalayas from the famous Nagarkot viewpoint.",
    highlights: ["Panoramic Himalayan views", "Sunrise photography", "Local village exploration"],
    maxAltitude: "2,175m",
    groupSize: "2-15",
    bestSeason: "Year-round",
  },
  {
    id: "shivapuri-hike",
    title: "Shivapuri National Park Hike",
    category: "hiking",
    image: "/placeholder.svg?height=400&width=600",
    duration: "1 Day",
    difficulty: "Easy",
    price: 75,
    description: "A refreshing day hike through lush forests with stunning views of Kathmandu Valley.",
    highlights: ["Dense forest trails", "Bird watching", "Kathmandu Valley views"],
    maxAltitude: "2,732m",
    groupSize: "2-20",
    bestSeason: "Year-round",
  },
  {
    id: "poon-hill-hike",
    title: "Poon Hill Sunrise Hike",
    category: "hiking",
    image: "/placeholder.svg?height=400&width=600",
    duration: "4 Days",
    difficulty: "Easy",
    price: 450,
    description: "One of the most popular short hikes with breathtaking views of Annapurna and Dhaulagiri.",
    highlights: ["Ghorepani village", "Sunrise at Poon Hill", "Rhododendron forests"],
    maxAltitude: "3,210m",
    groupSize: "2-15",
    bestSeason: "Mar-May, Sep-Nov",
  },
  {
    id: "chandragiri-hike",
    title: "Chandragiri Hills Hike",
    category: "hiking",
    image: "/placeholder.svg?height=400&width=600",
    duration: "1 Day",
    difficulty: "Easy",
    price: 85,
    description: "Experience cable car ride and hiking with panoramic views of Kathmandu and Himalayas.",
    highlights: ["Cable car experience", "Bhaleshwor Temple", "360-degree mountain views"],
    maxAltitude: "2,551m",
    groupSize: "2-20",
    bestSeason: "Year-round",
  },
  // Discovery Packages
  {
    id: "upper-mustang",
    title: "Upper Mustang Discovery",
    category: "discovery",
    image: "/placeholder.svg?height=400&width=600",
    duration: "14 Days",
    difficulty: "Moderate",
    price: 2400,
    description: "Explore the forbidden kingdom with its ancient Buddhist culture and lunar landscapes.",
    highlights: ["Lo Manthang walled city", "Ancient cave monasteries", "Tibetan culture"],
    maxAltitude: "3,840m",
    groupSize: "2-10",
    bestSeason: "Mar-Nov",
  },
  {
    id: "dolpo-region",
    title: "Dolpo Discovery Trek",
    category: "discovery",
    image: "/placeholder.svg?height=400&width=600",
    duration: "21 Days",
    difficulty: "Challenging",
    price: 3500,
    description: "One of the most remote and pristine regions of Nepal, untouched by modernity.",
    highlights: ["Shey Phoksundo Lake", "Ancient Bon culture", "Remote villages"],
    maxAltitude: "5,190m",
    groupSize: "2-8",
    bestSeason: "May-Oct",
  },
  {
    id: "tsum-valley",
    title: "Tsum Valley Trek",
    category: "discovery",
    image: "/placeholder.svg?height=400&width=600",
    duration: "15 Days",
    difficulty: "Moderate",
    price: 1900,
    description: "The sacred hidden valley with rich Tibetan Buddhist heritage and untouched culture.",
    highlights: ["Mu Gompa", "Milarepa's cave", "Traditional Tsum villages"],
    maxAltitude: "3,700m",
    groupSize: "2-10",
    bestSeason: "Mar-May, Sep-Nov",
  },
  // Cultural Tours
  {
    id: "kathmandu-heritage",
    title: "Kathmandu Valley Heritage",
    category: "cultural",
    image: "/placeholder.svg?height=400&width=600",
    duration: "5 Days",
    difficulty: "Easy",
    price: 650,
    description: "Discover the UNESCO World Heritage sites of the Kathmandu Valley.",
    highlights: ["Pashupatinath Temple", "Boudhanath Stupa", "Three Durbar Squares"],
    maxAltitude: "1,400m",
    groupSize: "2-15",
    bestSeason: "Year-round",
  },
  {
    id: "buddhist-pilgrimage",
    title: "Buddhist Pilgrimage Tour",
    category: "cultural",
    image: "/placeholder.svg?height=400&width=600",
    duration: "8 Days",
    difficulty: "Easy",
    price: 950,
    description: "Visit the sacred Buddhist sites including Buddha's birthplace in Lumbini.",
    highlights: ["Lumbini", "Swayambhunath", "Kopan Monastery", "Meditation sessions"],
    maxAltitude: "1,400m",
    groupSize: "2-15",
    bestSeason: "Year-round",
  },
  {
    id: "village-homestay",
    title: "Village Homestay Experience",
    category: "cultural",
    image: "/placeholder.svg?height=400&width=600",
    duration: "7 Days",
    difficulty: "Easy",
    price: 800,
    description: "Live with local families and experience authentic Nepali village life.",
    highlights: ["Traditional cooking", "Farming activities", "Local festivals", "Craft workshops"],
    maxAltitude: "2,000m",
    groupSize: "2-8",
    bestSeason: "Year-round",
  },
  // Cycling Packages
  {
    id: "kathmandu-valley-cycling",
    title: "Kathmandu Valley Cycling",
    category: "cycling",
    image: "/placeholder.svg?height=400&width=600",
    duration: "3 Days",
    difficulty: "Easy",
    price: 350,
    description: "Explore the historic Kathmandu Valley by bike, visiting temples and traditional villages.",
    highlights: ["Bhaktapur Durbar Square", "Changu Narayan Temple", "Scenic rice paddies"],
    maxAltitude: "1,500m",
    groupSize: "2-12",
    bestSeason: "Year-round",
  },
  {
    id: "annapurna-cycling",
    title: "Annapurna Mountain Biking",
    category: "cycling",
    image: "/placeholder.svg?height=400&width=600",
    duration: "10 Days",
    difficulty: "Challenging",
    price: 1450,
    description: "An epic mountain biking adventure through the Annapurna region's diverse landscapes.",
    highlights: ["Pokhara lakeside", "Mountain trails", "Traditional Gurung villages"],
    maxAltitude: "3,800m",
    groupSize: "2-8",
    bestSeason: "Mar-May, Sep-Nov",
  },
  {
    id: "mustang-cycling",
    title: "Upper Mustang Cycling",
    category: "cycling",
    image: "/placeholder.svg?height=400&width=600",
    duration: "14 Days",
    difficulty: "Challenging",
    price: 2200,
    description: "Cycle through the mystical kingdom of Mustang with its unique desert landscapes.",
    highlights: ["Lo Manthang", "Ancient caves", "Tibetan Buddhist culture"],
    maxAltitude: "3,840m",
    groupSize: "2-8",
    bestSeason: "Mar-Nov",
  },
  {
    id: "chitwan-cycling",
    title: "Chitwan Jungle Cycling",
    category: "cycling",
    image: "/placeholder.svg?height=400&width=600",
    duration: "4 Days",
    difficulty: "Easy",
    price: 420,
    description: "Combine cycling with wildlife exploration in the famous Chitwan National Park.",
    highlights: ["Jungle trails", "Wildlife viewing", "Tharu village visits"],
    maxAltitude: "200m",
    groupSize: "2-10",
    bestSeason: "Oct-Mar",
  },
]

export const categories = [
  { id: "all", label: "All Packages" },
  { id: "trekking", label: "Trekking" },
  { id: "climbing", label: "Climbing" },
  { id: "hiking", label: "Hiking" },
  { id: "discovery", label: "Discovery Sites" },
  { id: "cultural", label: "Cultural Tours" },
  { id: "cycling", label: "Cycling" },
]

export const difficulties = ["Easy", "Moderate", "Challenging", "Extreme"]
